default:
  image: node:20.11.0

stages:
  - deploy
  - test
  - lint
  - preview



preview:
  stage: deploy
  except:
    - master
  script:
    - cd src/nextapp
    - npm install
    - cd ..
    - npm install -g vercel
    - vercel pull --yes --environment=preview  --token=$VERCEL_TOKEN
    - vercel deploy --token=$VERCEL_TOKEN


production:
  stage: deploy
  only:
    - master
  script:
    - cd src/nextapp
    - npm install
    - cd ..
    - npm install -g vercel
    - vercel pull --yes --environment=production  --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --token=$VERCEL_TOKEN
build:
  stage: test
  script:
    - cd src/nextapp
    - npm install
    - npm run build




